name: Agentum CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install uv
      run: pip install uv

    - name: Install dependencies (including dev tools)
      run: uv pip install --system -e ".[dev]"

    - name: Run linter and formatter check
      run: |
        uv run ruff check .
        uv run ruff format --check .

    - name: Run Unit and Logic Tests (Skip Integration Tests)
      run: uv run pytest -m "not integration"
